name: "Tidelift Alignment"
description: "Ensures all software being used is a part of your Tidelift catalog"
author: "Jeremy Katz"
branding:
  icon: "alert-circle"
  color: "orange"
runs:
  using: "docker"
  image: "Dockerfile"
